name: 'Build and Deploy Documentation Site'
description: 'Convert Markdown documentation to a BCC documentation site'
inputs:
  title:
    description: 'Title of the generated website'
    required: true
    default: ${{ github.event.repository.name }}
  description:
    description: 'Description of the generated website, used for the head meta tag'
    required: true
    default: ${{ github.event.repository.description }}
  docs-dir:
    description: 'Directory where the docs are located'
    required: false
    default: 'docs'
  branch:
    description: 'Which branch to use for "Edit this page on GitHub" links'
    required: false
    default: 'main'
runs:
  using: "composite"
  steps:
    - name: Check out base repository
      uses: actions/checkout@v3
      with:
        repository: bcc-code/bcc-documentation-base

    - name: Check out current repository
      uses: actions/checkout@v3
      with:
        path: source

    - name: Copy documentation to VuePress theme
      shell: bash
      run: |
        cd source
        cp -r ./${{ inputs.docs-dir }}/* $GITHUB_WORKSPACE/vuepress/docs/

    - uses: microsoft/variable-substitution@v1
      with:
        files: "vuepress/docs/.vuepress/data.json"
      env:
        title: ${{ inputs.title }}
        description: ${{ inputs.description }}
        base: /${{ github.event.repository.name }}/
        docsRepo: ${{ github.repository }}
        docsDir: ${{ inputs.docs-dir }}

    - name: Build VuePress site
      shell: bash
      run: |
        cd vuepress
        npm i && npm run build

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: vuepress/docs/.vuepress/dist