name: "Build and Deploy Documentation Site"
description: "Convert Markdown documentation to a BCC documentation site"
inputs:
  title:
    description: "Title of the generated website"
    required: true
    default: ${{ github.event.repository.name }}
  description:
    description: "Description of the generated website, used for the head meta tag"
    required: true
    default: ${{ github.event.repository.description }}
  docs-dir:
    description: "Directory where the docs are located"
    required: false
    default: "docs"
  branch:
    description: 'Which branch to use for "Edit this page on GitHub" links'
    required: false
    default: "main"
  base:
    description: "The base url for the website"
    required: false
    default: /docs
  collapse-sidebar:
    description: "Whether to collapse sidebar sections by default"
    required: false
    default: false
  auto-register-components:
    description: "Whether to automatically register Vue components"
    required: false
    default: false
  components-dir:
    description: "The directory from where Vue components should automatically be registered"
    required: false
    default: "src/components"
  debug-build:
    description: "Whether or not to enable debugging for the Vite build"
    required: false
    default: false
  public:
    description: "Whether or not to make the documentation publicly available (only works for private repositories)"
    required: false
    default: false
  authentication:
    description: "Which provider to use for the login flow when accessing the documentation"
    required: false
    default: "github"
  root:
    description: "Whether or not to deploy the site to the root of the custom container (true) or to a subfolder named after the repository (false)"
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - name: Check out base repository
      uses: actions/checkout@v3
      with:
        repository: bcc-code/bcc-documentation-base

    - name: Check out current repository
      uses: actions/checkout@v3
      with:
        path: source

    - name: Zip Markdown files
      shell: bash
      run: |
        cd source/${{ inputs.docs-dir }}
        zip -r MarkdownDocs.zip .

    - uses: microsoft/variable-substitution@v1
      with:
        files: "vuepress/docs/.vuepress/data.json"
      env:
        title: ${{ inputs.title }}
        description: ${{ inputs.description }}
        base: ${{ inputs.base }}
        docsRepo: ${{ github.repository }}
        docsDir: ${{ inputs.docs-dir }}
        docsBranch: ${{ inputs.branch }}
        collapseSidebarSections: ${{ inputs.collapse-sidebar }}
        autoRegisterComponents: ${{ inputs.auto-register-components }}

    - name: Get Token from GitHub
      id: token
      shell: bash
      run: |
        curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://github.com/bcc-code" | jq -r ".value" | echo -e "token=$(</dev/stdin)\n" >> $GITHUB_OUTPUT

    - name: Upload Markdown files to azure storage
      shell: bash
      run: |
        curl --request POST \
          --header "Authorization: Bearer ${{steps.token.outputs.token}}" \
          --header 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36' \
          --form Docs=@source/${{ inputs.docs-dir }}/MarkdownDocs.zip \
          "https://developer.bcc.no/UploadMdContainer?aggregateContainer=mddocs&root=${{inputs.root}}"

    - name: Download Markdown files from azure storage
      shell: bash
      run: |
        cd vuepress/docs/
        curl --request GET \
          --header "Authorization: Bearer ${{steps.token.outputs.token}}" \
          --header 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36' \
          "https://developer.bcc.no/GetDoc?container=mddocs" \
          --output MarkdownDocs.zip
        unzip -o MarkdownDocs.zip

    - name: Build VuePress site
      shell: bash
      run: |
        chmod -R u+rwX vuepress/docs || true
        cd vuepress
        npm ci && ${{ inputs.debug-build == true && 'DEBUG=*' || '' }} npm run build ${{ inputs.debug-build == true && '-- --debug' || '' }}

    - name: Zips built site files
      shell: bash
      run: |
        cd vuepress/docs/.vuepress/dist
        zip -r Docs.zip .

    - name: Upload VuePress site
      shell: bash
      run: |
        curl --request POST \
          --header "Authorization: Bearer ${{steps.token.outputs.token}}" \
          --header 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36' \
          --form Docs=@vuepress/docs/.vuepress/dist/Docs.zip \
          "https://developer.bcc.no/UploadDoc?isPublic=${{inputs.public}}&auth=${{inputs.authentication}}&customContainerName=docs"
