name: 'Build and Deploy Documentation Site'
description: 'Convert Markdown documentation to a BCC documentation site'
inputs:
  title:
    description: 'Title of the generated website'
    required: true
    default: ${{ github.event.repository.name }}
  description:
    description: 'Description of the generated website, used for the head meta tag'
    required: true
    default: ${{ github.event.repository.description }}
  docs-dir:
    description: 'Directory where the docs are located'
    required: false
    default: 'docs'
  branch:
    description: 'Which branch to use for "Edit this page on GitHub" links'
    required: false
    default: 'main'
  base:
    description: 'The base url for the website'
    required: false
    default: /${{ github.event.repository.name }}/
  collapse-sidebar:
    description: 'Whether to collapse sidebar sections by default'
    required: false
    default: false
  auto-register-components:
    description: 'Whether to automatically register Vue components'
    required: false
    default: false
  components-dir:
    description: 'The directory from where Vue components should automatically be registered'
    required: false
    default: 'src/components'
runs:
  using: "composite"
  steps:
    - name: Check out base repository
      uses: actions/checkout@v3
      with:
        repository: bcc-code/bcc-documentation-base

    - name: Check out current repository
      uses: actions/checkout@v3
      with:
        path: source

    - name: Copy documentation to VuePress theme
      shell: bash
      run: |
        cd source
        cp -r ./${{ inputs.docs-dir }}/* $GITHUB_WORKSPACE/vuepress/docs/
        ${{ inputs.auto-register-components }} && mkdir $GITHUB_WORKSPACE/vuepress/docs/.vuepress/auto-register-components/
        ${{ inputs.auto-register-components }} && cp -r ./${{ inputs.components-dir }}/* $GITHUB_WORKSPACE/vuepress/docs/.vuepress/auto-register-components/
        true

    - uses: microsoft/variable-substitution@v1
      with:
        files: "vuepress/docs/.vuepress/data.json"
      env:
        title: ${{ inputs.title }}
        description: ${{ inputs.description }}
        base: ${{ inputs.base }}
        docsRepo: ${{ github.repository }}
        docsDir: ${{ inputs.docs-dir }}
        docsBranch: ${{ inputs.branch }}
        collapseSidebarSections: ${{ inputs.collapse-sidebar }}
        autoRegisterComponents: ${{ inputs.auto-register-components }}

    - name: Build VuePress site
      shell: bash
      run: |
        cd vuepress
        npm ci && npm run build

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: vuepress/docs/.vuepress/dist