name: Build and Deploy Documentation Site

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master","main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out base repository
        uses: actions/checkout@v2
        with:
          repository: bcc-code/bcc-documentation-base

      - name: Check out current repository
        uses: actions/checkout@v2
        with:
          path: source

      - name: Copy documentation to VuePress theme
        run: |
          cd source
          cp -r ./docs/* $GITHUB_WORKSPACE/vuepress/docs/
      - uses: microsoft/variable-substitution@v1
        with:
          files: "vuepress/docs/.vuepress/data.json"
        env:
          title: Documentation Guide
          description: Information on how to set up documentation for BCC projects
          base: /${{ github.event.repository.name }}/
          docsRepo: ${{ github.repository }}

      - name: Build VuePress site
        run: |
          cd vuepress
          npm i && npm run build
     
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: vuepress/docs/.vuepress/dist
        
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1